version: '3.7'

services:
  nginx:
    image: nginx:1.25.3
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - /var/www/certbot/:/var/www/certbot/:ro
      - /etc/letsencrypt/live/diablostrike.com/:/etc/letsencrypt/live/diablostrike.com/:ro
      - /etc/letsencrypt/archive/diablostrike.com/:/etc/letsencrypt/archive/diablostrike.com/:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - ds_net

networks:
  ds_net:
    external: true
